//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbladmin
    {
        public int AD_ID { get; set; }
        public string F_Name { get; set; }
        public string L_Name { get; set; }
        public string E_mail { get; set; }
        public string Password { get; set; }
        public string A_Image { get; set; }
    }
}
