//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatchdetail
    {
        public int BD_ID { get; set; }
        public Nullable<int> B_ID { get; set; }
        public Nullable<int> S_ID { get; set; }
    
        public virtual tblbatch tblbatch { get; set; }
        public virtual tblstudent tblstudent { get; set; }
    }
}
