//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblstudent()
        {
            this.tblbatchdetails = new HashSet<tblbatchdetail>();
        }
    
        public int S_ID { get; set; }
        public string F_Name { get; set; }
        public string L_Name { get; set; }
        public string E_mail { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public Nullable<int> ST_ID { get; set; }
        public Nullable<int> CT_ID { get; set; }
        public Nullable<int> Mobile { get; set; }
        public string Status { get; set; }
        public string S_img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbatchdetail> tblbatchdetails { get; set; }
        public virtual tblstate tblstate { get; set; }
    }
}
